### ISSUE TITLE
Requests for point and wave

### ISSUE THREAD

**Issue by paramat** [minetest-mods/emote#2]
I love the concept of this mod. 2 requests:
Wave is barely noticeable and seems like a handshake, i think wave needs to be visible from a distance, arm raised almost straight up and moving from side to side.
Point points slightly downward, please could the arm extend out horizontally?

Another emote idea: surrender, 'hands up'.

**Comment by sofar** [comment]
There is no usable animation part of the default model that would allow us to do any of this.

**Comment by paramat** [comment]
So the emotes are limited to parts of already present animations? Sorry didn't realise.
Is there a part of the digging animation that has the arm more horizontal, for pointing and waving?

**Comment by sofar** [comment]
I've tried different frames, but this is the best I could come up with :)

Note: /wave is only 5 frames:

https://github.com/minetest-mods/emote/blob/master/init.lua#L20

**Comment by sofar** [comment]
The only solution to do this without redoing the model itself is to provide code to handle bone animation. The problem with that is that it's super laggy, and I really don't want to do it for just that reason alone. The second reason is that doing bone animation would require me to move bones every server step, and so this would require extensive synchronization, another reason not to: it would be very difficult to get a bad looking result.

**Comment by sofar** [comment]
Obviously this results in the conclusion that we should, at one point, collect desirable gesture animations and add them to the default character model in `minetest_game`.

I'd love to /dance, myself. But /cry, /cheer, /shy and a few others are likely popular options.

**Comment by paramat** [comment]
Ok i see, thanks.
